-- Sync tool_registry descriptions from platform_contracts/tool_catalog.py

UPDATE platform_core.tool_registry SET description = 'Клик по элементу через CSS selector или ref из browser.snapshot.' WHERE name = 'browser.click';
UPDATE platform_core.tool_registry SET description = 'Закрыть браузерную сессию и все вкладки.' WHERE name = 'browser.close_session';
UPDATE platform_core.tool_registry SET description = 'Извлечь текст со страницы, по URL или DuckDuckGo-поиск через query. selector по умолчанию body.' WHERE name = 'browser.extract_text';
UPDATE platform_core.tool_registry SET description = 'Полностью заменить значение input (clear + type).' WHERE name = 'browser.fill';
UPDATE platform_core.tool_registry SET description = 'Перейти по URL в активной вкладке. URL должен быть в allowlist worker.' WHERE name = 'browser.navigate';
UPDATE platform_core.tool_registry SET description = 'Открыть эфемерную браузерную сессию Playwright (cookies живут до close_session). run_id агента связывает вкладки одного прогона.' WHERE name = 'browser.open_session';
UPDATE platform_core.tool_registry SET description = 'PNG-скриншот активной страницы (path в ответе). full_page — вся прокрутка.' WHERE name = 'browser.screenshot';
UPDATE platform_core.tool_registry SET description = 'Снимок интерактивных элементов страницы (ref, role, name, selector). Вызывайте перед browser.click / browser.type.' WHERE name = 'browser.snapshot';
UPDATE platform_core.tool_registry SET description = 'Управление вкладками: action=list|new|switch.' WHERE name = 'browser.tabs';
UPDATE platform_core.tool_registry SET description = 'Ввод текста в поле. submit=true — Enter после ввода. password=true — скрытый ввод.' WHERE name = 'browser.type';
UPDATE platform_core.tool_registry SET description = 'Ждать selector/ref, URL glob или sleep_ms.' WHERE name = 'browser.wait';
UPDATE platform_core.tool_registry SET description = 'Подключиться к COM-приложению (Outlook, Excel, 1C через legacy bridge). app — ключ из com.list_apps или progid явно.' WHERE name = 'com.connect';
UPDATE platform_core.tool_registry SET description = 'Вызов метода COM-объекта generic bridge (session_id из com.connect).' WHERE name = 'com.invoke';
UPDATE platform_core.tool_registry SET description = 'Список зарегистрированных COM-приложений на Windows host (onec, outlook, excel, word…). Используйте перед com.connect.' WHERE name = 'com.list_apps';
UPDATE platform_core.tool_registry SET description = 'Одна встреча Outlook по EntryID из calendar_list.' WHERE name = 'com.outlook.calendar_get';
UPDATE platform_core.tool_registry SET description = 'Список встреч календаря Outlook за период (days от сегодня или start/end ISO). Требует session_id из com.outlook.launch.' WHERE name = 'com.outlook.calendar_list';
UPDATE platform_core.tool_registry SET description = 'Закрыть COM-сессию Outlook. quit=true — завершить процесс Outlook.' WHERE name = 'com.outlook.close';
UPDATE platform_core.tool_registry SET description = 'Запустить Microsoft Outlook через COM на Windows host. Возвращает session_id.' WHERE name = 'com.outlook.launch';
UPDATE platform_core.tool_registry SET description = 'Закрыть generic COM-сессию.' WHERE name = 'com.release';
UPDATE platform_core.tool_registry SET description = 'Каталог пакетов desktop host (:7830): com, fs, shell, desktop tools. Вызывайте первым для проверки доступности host-инструментов.' WHERE name = 'desktop.capabilities';
UPDATE platform_core.tool_registry SET description = 'Прочитать текст из буфера обмена Windows (Unicode).' WHERE name = 'desktop.clipboard_read';
UPDATE platform_core.tool_registry SET description = 'Записать текст в буфер обмена Windows.' WHERE name = 'desktop.clipboard_write';
UPDATE platform_core.tool_registry SET description = 'Открыть файл или каталог приложением по умолчанию (Windows shell).' WHERE name = 'desktop.open_path';
UPDATE platform_core.tool_registry SET description = 'Информация о Windows desktop host: OS, Python, hostname, user, cwd.' WHERE name = 'desktop.system_info';
UPDATE platform_core.tool_registry SET description = 'Создать .docx или .xlsx по указанному path (OOXML, без Word/Excel). Агент сам задаёт полный путь внутри FS_ROOT_ALLOWLIST. format: docx|xlsx (или по расширению path). Для xlsx опционально rows: [[...]].' WHERE name = 'fs.build_office_file';
UPDATE platform_core.tool_registry SET description = 'Копировать файл внутри allowlist-корней.' WHERE name = 'fs.copy';
UPDATE platform_core.tool_registry SET description = 'Список файлов в allowlist-каталоге Windows host (:7830). path — относительный или абсолютный внутри разрешённых корней.' WHERE name = 'fs.list';
UPDATE platform_core.tool_registry SET description = 'Переместить файл/каталог внутри allowlist-корней.' WHERE name = 'fs.move';
UPDATE platform_core.tool_registry SET description = 'Прочитать файл из allowlist-корня. as_base64 для бинарных файлов.' WHERE name = 'fs.read';
UPDATE platform_core.tool_registry SET description = 'Метаданные файла или каталога (размер, mtime, is_dir).' WHERE name = 'fs.stat';
UPDATE platform_core.tool_registry SET description = 'Записать файл в allowlist-корень. mode: overwrite|append|create. Для бинарных файлов (.docx, .xlsx) передайте content_base64. Путь задаётся явно в payload.path (полный путь в allowlist). Allowlist: C:\Users\Public\Documents, CONSTRUCTOR_ROOT, data\filesystem.' WHERE name = 'fs.write';
UPDATE platform_core.tool_registry SET description = 'Метаданные вложений письма (filename, size) по UID. Не скачивает содержимое на диск — только список.' WHERE name = 'imap.fetch_attachments';
UPDATE platform_core.tool_registry SET description = 'Прочитать письмо по UID: subject, from, body_text (plain, до ~12 КБ). UID берите из imap.search или imap.list_unread. После — imap.fetch_attachments для вложений.' WHERE name = 'imap.fetch_message';
UPDATE platform_core.tool_registry SET description = 'Список UID непрочитанных писем в общем IMAP-ящике (INBOX). Используйте перед imap.fetch_message. Не фильтрует по отправителю — для поиска берите imap.search.' WHERE name = 'imap.list_unread';
UPDATE platform_core.tool_registry SET description = 'Поиск писем в IMAP: критерий OR FROM needle SUBJECT needle (без полнотекстового TEXT). Возвращает последние limit совпадений (самые новые), не «первое найденное». Поля user или query — подстрока для FROM/SUBJECT; email в user даёт точный FROM.' WHERE name = 'imap.search';
UPDATE platform_core.tool_registry SET description = 'Прикрепить файл к документу 1С. В текущей сборке NOT_IMPLEMENTED — используйте ручное прикрепление или onec.odata_patch для метаданных.' WHERE name = 'onec.attach_file';
UPDATE platform_core.tool_registry SET description = 'Открыть COM-сеанс 1С ERP через V83.COMConnector под ERP_LOGIN. Возвращает session_id для onec.com.invoke / query_tasks / release. Только Windows host :7831.' WHERE name = 'onec.com.connect';
UPDATE platform_core.tool_registry SET description = 'Вызов разрешённого метода COM-объекта сеанса 1С: Connect, NewObject, Documents, GetObject, Quit, String, EvalExpr, BatchExecute. Требует session_id из onec.com.connect.' WHERE name = 'onec.com.invoke';
UPDATE platform_core.tool_registry SET description = 'Список задач исполнителя через COM-запрос в ERP (не OData, не GUI). По умолчанию: Задача.ЗадачаИсполнителя для текущего ERP-пользователя. prefer_crm=true — CRM_ЗадачиПользователей. НЕ возвращает задачи формы «Документооборот: Мои задачи» (1С:ДО) — они в другой интеграции. Ответ: tasks[] с number, description, date, due_date, executor; task_source; current_user.' WHERE name = 'onec.com.query_tasks';
UPDATE platform_core.tool_registry SET description = 'Закрыть COM-сеанс 1С ERP и освободить ресурсы на Windows host.' WHERE name = 'onec.com.release';
UPDATE platform_core.tool_registry SET description = 'Статус COM-сервиса 1С ERP (:7831, Windows 32-bit Python). Проверяет bitness, строку подключения, готовность COMConnector.' WHERE name = 'onec.com.status';
UPDATE platform_core.tool_registry SET description = 'HTTP GET к OData 1С ERP (документы, справочники). Учётные данные: ERP_LOGIN/ERP_PASSWORD из окружения или username/password в payload. HTTP 402 = неверный логин/пароль. path сохраняет query string ($top, $filter). Для задач исполнителя используйте onec.com.query_tasks, не OData.' WHERE name = 'onec.odata_get';
UPDATE platform_core.tool_registry SET description = 'Обновить объект 1С по ref_key через OData PATCH.' WHERE name = 'onec.odata_patch';
UPDATE platform_core.tool_registry SET description = 'Создать объект 1С через OData POST. entity — из allowlist сервиса. body — поля документа/справочника в JSON.' WHERE name = 'onec.odata_post';
UPDATE platform_core.tool_registry SET description = 'Read-only SELECT к SQL-базе ERP (pyodbc). Только запросы из allowlist сервиса. Макс. ~100 строк. Для документов предпочтительнее onec.odata_get.' WHERE name = 'onec.sql_query';
UPDATE platform_core.tool_registry SET description = 'Выполнить shell-команду. runtime=sandbox — изолированный Docker (:7823); runtime=native — Windows host (:7828/:7830) с allowlist команд (dir, type, git…). Без runtime — по SHELL_DEFAULT_RUNTIME. Возвращает stdout, stderr, exit_code.' WHERE name = 'shell.run';
