"""Backward-compatible facade for slot search (EWS)."""

from __future__ import annotations

from app.vendors.aiagentback.tools.Outlook.slot_search import *  # noqa: F403
from app.vendors.aiagentback.tools.Outlook.slot_search import (  # noqa: F401
    AvailabilitySource,
    setup_logging,
    combine,
    is_workday,
    next_workday_start,
    align_preferred,
    not_before_now,
    intervals_overlap,
    slot_respects_rules,
    advance_candidate,
    event_interval,
    freebusy_event_interval,
    parse_freebusy_events,
    freebusy_busy_intervals,
    freebusy_events_busy_intervals,
    fetch_all_busy_intervals,
    coalesce_intervals,
    merge_busy_intervals,
    is_free_for_attendee,
    is_free_for_all,
    partition_attendees_at_slot,
    union_busy_for_all,
    verify_slot_with_calendar,
    normalize_calendar_email,
    calendar_item_attendee_emails,
    movability_score,
    conflicting_events_at_slot,
    conflicting_intervals_at_slot,
    suggest_reschedule_window,
    build_conflict_records,
    movability_reason,
    conflicting_calendar_items_at_slot,
    dedupe_conflict_records,
    attach_reschedule_hints,
    iterate_slot_candidates,
    quorum_search_start,
    first_valid_slot_in_window,
    find_slot_via_busy_gaps,
    quorum_confidence,
    coverage_ratios,
    preliminary_slot_impact,
    slot_impact_score,
    find_quorum_slots,
    find_company_calendar_reschedule_candidates,
    find_nearest_slot,
    find_nearest_slots_per_attendee,
    build_slot_participant_details,
    format_slot,
    attach_room_status,
    dispatch_find_quorum_meeting_slots,
    dispatch_find_meeting_slot,
    dispatch_find_attendee_nearest_slots,
    build_parser,
    main,
)

